### ISSUE TITLE
conflicting licenses

### ISSUE THREAD

**Issue by jvanasco** [Crossway/antimarkdown#12]
just a heads-up -- `setup.py` says the license is BSD (https://github.com/Crossway/antimarkdown/blob/master/setup.py#L28), but then lists a classifier as 'License :: OSI Approved :: MIT License' (https://github.com/Crossway/antimarkdown/blob/master/setup.py#L34).  The included license appears to be MIT.

**Comment by eykd** [comment]
@jvanasco Thanks for catching that.
